#!/bin/bash

# ButterNotes Installation Script - ButterBash Extension

set -e

BUTTERNOTES_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Function to ask yes/no questions
ask_yes_no() {
    local prompt="$1"
    local response

    while true; do
        read -p "$prompt [y/n]: " response
        case "${response,,}" in
            y|yes) return 0 ;;
            n|no) return 1 ;;
            *) echo "Please answer yes or no." ;;
        esac
    done
}

echo "🧈 Installing ButterNotes..."
echo

# ButterNotes is a universal tool that works with any shell
echo "🧈 ButterNotes works with any shell (bash, zsh, fish)"
echo "   Optional: ButterBash provides enhanced shell experience"
echo

# Check dependencies
echo "Checking dependencies..."
missing_deps=""

# Core dependencies
command -v bash >/dev/null 2>&1 || missing_deps="$missing_deps bash"

# Optional but recommended
optional_deps=""
command -v xclip >/dev/null 2>&1 || command -v wl-paste >/dev/null 2>&1 || optional_deps="$optional_deps xclip/wl-clipboard"

if [ -n "$missing_deps" ]; then
    echo "❌ Missing required dependencies:$missing_deps"
    echo "Please install them and run this script again."
    exit 1
fi

if [ -n "$optional_deps" ]; then
    echo "⚠️  Optional dependencies not found:$optional_deps"
    echo "   Some features may not work without these."
    echo
fi

# Configure notes location
echo "📁 Where should your notes be stored?"
echo
echo "1) ~/Documents/ButterNotes/  (Recommended for mobile sync)"
echo "2) ~/notes/                   (Simple local storage)"
echo "3) ~/Nextcloud/Notes/         (Nextcloud sync)"
echo "4) ~/Dropbox/Notes/           (Dropbox sync)"
echo "5) Custom location"
echo
read -p "Choose [1-5] (default: 1): " choice

case "${choice:-1}" in
    1)
        NOTES_DIR="$HOME/Documents/ButterNotes"
        ;;
    2)
        NOTES_DIR="$HOME/notes"
        ;;
    3)
        NOTES_DIR="$HOME/Nextcloud/Notes"
        ;;
    4)
        NOTES_DIR="$HOME/Dropbox/Notes"
        ;;
    5)
        read -p "Enter custom path: " NOTES_DIR
        # Expand tilde if present
        NOTES_DIR="${NOTES_DIR/#\~/$HOME}"
        ;;
    *)
        NOTES_DIR="$HOME/Documents/ButterNotes"
        ;;
esac

echo
echo "📝 Notes will be stored in: $NOTES_DIR"

# Check for existing notes to migrate
echo
if [ -f "$HOME/.notes" ] || [ -f "$HOME/.tasks" ]; then
    echo "📦 Found existing notes/todos. They will be migrated on first use."
fi

# Create ButterNotes config directory
CONFIG_DIR="$HOME/.config/butternotes"
mkdir -p "$CONFIG_DIR"

# Create config file
CONFIG_FILE="$CONFIG_DIR/butter.conf"
cat > "$CONFIG_FILE" << EOF
#!/bin/bash
# ButterNotes Configuration
# Generated by install.sh on $(date)

# Notes directory - change this to sync with mobile apps
BUTTER_NOTES_DIR="$NOTES_DIR"

# File names with .md extension for mobile compatibility
NOTES_FILE="\$BUTTER_NOTES_DIR/notes.md"
TODOS_FILE="\$BUTTER_NOTES_DIR/todos.md"

# Legacy paths (for migration)
LEGACY_NOTES_FILE="\$HOME/.notes"
LEGACY_TODOS_FILE="\$HOME/.tasks"

# Editor preference
BUTTER_EDITOR="\${BUTTER_EDITOR:-\${EDITOR:-nano}}"

# Create notes directory if it doesn't exist
mkdir -p "\$BUTTER_NOTES_DIR"
EOF

echo "✅ Configuration saved to $CONFIG_FILE"

# Copy project templates
echo "📄 Installing project templates..."
TEMPLATES_DIR="$CONFIG_DIR/templates"
mkdir -p "$TEMPLATES_DIR"
if [ -d "$BUTTERNOTES_DIR/config/templates" ]; then
    cp "$BUTTERNOTES_DIR/config/templates/"*.md "$TEMPLATES_DIR/" 2>/dev/null || true
    echo "✅ Templates installed to $TEMPLATES_DIR"
else
    echo "⚠️  Template directory not found, skipping..."
fi

# Add ButterNotes to PATH
echo
echo "📦 Installing ButterNotes executable..."

# Create symlink in local bin directory
mkdir -p "$HOME/.local/bin"
BUTTER_EXECUTABLE="$HOME/.local/bin/butter"

if [ -f "$BUTTERNOTES_DIR/bin/butter" ]; then
    if [ -f "$BUTTER_EXECUTABLE" ]; then
        echo "⚠️  ButterNotes executable already exists"
        if ask_yes_no "Replace existing executable?"; then
            cp "$BUTTERNOTES_DIR/bin/butter" "$BUTTER_EXECUTABLE"
            chmod +x "$BUTTER_EXECUTABLE"
            echo "✅ Executable updated"
        fi
    else
        cp "$BUTTERNOTES_DIR/bin/butter" "$BUTTER_EXECUTABLE"
        chmod +x "$BUTTER_EXECUTABLE"
        echo "✅ Executable installed to ~/.local/bin/butter"
    fi
else
    echo "❌ Butter executable not found in ButterNotes directory"
    exit 1
fi

# Ask about aliases
echo
echo "🔗 Add ButterNotes aliases?"
echo "This will add convenient shortcuts like 'b' for butter, 'bc' for butter clip."
echo
if ask_yes_no "Add aliases?"; then
    # Create aliases content
    ALIASES_CONTENT='# ButterNotes aliases
# Provides convenient shortcuts for note-taking and todo management

# Main aliases
alias b="butter"                   # Interactive ButterNotes
alias bc="butter clip"             # Save clipboard as note
alias bt="butter todo"             # Add todo
alias bp="butter project"          # Project manager
alias bn="butter"                  # ButterNotes shorthand
alias butternotes="butter"         # Full name alias

# Quick shortcuts
alias n="butter add"               # Quick note (not interactive)
alias nl="butter list"             # List notes
alias t="butter todo"              # Quick todo (not interactive)
alias tl="butter todos"            # List todos
alias p="butter project"           # Quick project (not interactive)
alias pl="butter projects"         # List projects'

    # Create ButterNotes alias file
    ALIASES_FILE="$HOME/.config/butternotes/aliases.bash"
    echo "$ALIASES_CONTENT" > "$ALIASES_FILE"
    echo "✅ ButterNotes aliases created at $ALIASES_FILE"

    echo
    echo "📁 Where should the aliases be sourced?"
    echo "  1) ~/.bashrc (bash users)"
    echo "  2) ~/.zshrc (zsh users)"
    echo "  3) ~/.config/fish/config.fish (fish users)"
    echo "  4) ButterBash (~/.config/bash/aliases.bash)"
    echo "  5) Skip auto-sourcing (manual setup)"
    echo
    read -p "Choose [1-5] (default: detect shell): " alias_choice

    case "${alias_choice:-auto}" in
        1|bashrc)
            TARGET_FILE="$HOME/.bashrc"
            SOURCE_LINE="source $ALIASES_FILE"
            ;;
        2|zshrc)
            TARGET_FILE="$HOME/.zshrc"
            SOURCE_LINE="source $ALIASES_FILE"
            ;;
        3|fish)
            # Fish uses different syntax, create separate fish alias file
            FISH_ALIASES_FILE="$HOME/.config/butternotes/aliases.fish"
            FISH_ALIASES_CONTENT='# ButterNotes aliases for fish shell
# Provides convenient shortcuts for note-taking and todo management

# Main aliases
alias b="butter"                   # Interactive ButterNotes
alias bc="butter clip"             # Save clipboard as note
alias bt="butter todo"             # Add todo
alias bp="butter project"          # Project manager
alias bn="butter"                  # ButterNotes shorthand
alias butternotes="butter"         # Full name alias

# Quick shortcuts
alias n="butter add"               # Quick note (not interactive)
alias nl="butter list"             # List notes
alias t="butter todo"              # Quick todo (not interactive)
alias tl="butter todos"            # List todos
alias p="butter project"           # Quick project (not interactive)
alias pl="butter projects"         # List projects'

            echo "$FISH_ALIASES_CONTENT" > "$FISH_ALIASES_FILE"
            TARGET_FILE="$HOME/.config/fish/config.fish"
            SOURCE_LINE="source $FISH_ALIASES_FILE"
            echo "✅ Fish aliases created at $FISH_ALIASES_FILE"
            ;;
        4|butterbash)
            TARGET_FILE="$HOME/.config/bash/aliases.bash"
            SOURCE_LINE="source $ALIASES_FILE"
            ;;
        5|skip)
            echo "⏭️  Skipped auto-sourcing"
            echo "📝 To enable aliases, add this line to your shell config:"
            echo "   source $ALIASES_FILE"
            TARGET_FILE=""
            ;;
        auto|"")
            # Auto-detect current shell and existing files
            if [ -n "$ZSH_VERSION" ] && [ -f "$HOME/.zshrc" ]; then
                TARGET_FILE="$HOME/.zshrc"
                SOURCE_LINE="source $ALIASES_FILE"
                echo "🔍 Detected zsh, using ~/.zshrc"
            elif [ -n "$BASH_VERSION" ] && [ -f "$HOME/.bashrc" ]; then
                TARGET_FILE="$HOME/.bashrc"
                SOURCE_LINE="source $ALIASES_FILE"
                echo "🔍 Detected bash, using ~/.bashrc"
            elif [ "$(basename "$SHELL")" = "fish" ] && [ -f "$HOME/.config/fish/config.fish" ]; then
                # Fish uses different syntax, create separate fish alias file
                FISH_ALIASES_FILE="$HOME/.config/butternotes/aliases.fish"
                FISH_ALIASES_CONTENT='# ButterNotes aliases for fish shell
# Provides convenient shortcuts for note-taking and todo management

# Main aliases
alias b="butter"                   # Interactive ButterNotes
alias bc="butter clip"             # Save clipboard as note
alias bt="butter todo"             # Add todo
alias bp="butter project"          # Project manager
alias bn="butter"                  # ButterNotes shorthand
alias butternotes="butter"         # Full name alias

# Quick shortcuts
alias n="butter add"               # Quick note (not interactive)
alias nl="butter list"             # List notes
alias t="butter todo"              # Quick todo (not interactive)
alias tl="butter todos"            # List todos
alias p="butter project"           # Quick project (not interactive)
alias pl="butter projects"         # List projects'

                echo "$FISH_ALIASES_CONTENT" > "$FISH_ALIASES_FILE"
                TARGET_FILE="$HOME/.config/fish/config.fish"
                SOURCE_LINE="source $FISH_ALIASES_FILE"
                echo "🔍 Detected fish, using ~/.config/fish/config.fish"
                echo "✅ Fish aliases created at $FISH_ALIASES_FILE"
            elif [ -f "$HOME/.config/bash/aliases.bash" ]; then
                TARGET_FILE="$HOME/.config/bash/aliases.bash"
                SOURCE_LINE="source $ALIASES_FILE"
                echo "🔍 Detected ButterBash, using ~/.config/bash/aliases.bash"
            elif [ -f "$HOME/.bashrc" ]; then
                TARGET_FILE="$HOME/.bashrc"
                SOURCE_LINE="source $ALIASES_FILE"
                echo "🔍 Using ~/.bashrc"
            elif [ -f "$HOME/.zshrc" ]; then
                TARGET_FILE="$HOME/.zshrc"
                SOURCE_LINE="source $ALIASES_FILE"
                echo "🔍 Using ~/.zshrc"
            else
                echo "📝 No shell config detected. Add this line to your shell config:"
                echo "   source $ALIASES_FILE"
                TARGET_FILE=""
            fi
            ;;
        *)
            echo "❌ Invalid choice"
            exit 1
            ;;
    esac

    if [ -n "$TARGET_FILE" ]; then
        # Check if source line is already present
        if grep -q "source.*butternotes/aliases.bash" "$TARGET_FILE" 2>/dev/null; then
            echo "✅ ButterNotes aliases already sourced in $TARGET_FILE"
        else
            echo "" >> "$TARGET_FILE"
            echo "# ButterNotes aliases" >> "$TARGET_FILE"
            echo "$SOURCE_LINE" >> "$TARGET_FILE"
            echo "✅ ButterNotes sourcing added to $TARGET_FILE"
            echo "🔄 Reload your shell or run: source $TARGET_FILE"
        fi
    fi
else
    echo "⏭️  Skipped aliases installation"
fi

echo
echo "✅ Installation complete!"
echo
echo "📚 Quick start:"
echo "  1. Reload your shell: source ~/.bashrc"
echo "  2. Try: note \"My first note\""
echo "  3. Try: todo \"My first task\""
echo "  4. List notes: note"
echo "  5. List todos: todo"
if [ -f "$HOME/.config/bash/butternotes-aliases.bash" ]; then
    echo "  6. Use shortcuts: n, t, nc (note clip), etc."
fi
echo
echo "Notes location: $NOTES_DIR"
echo "Config file: $CONFIG_FILE"
echo "Executable: ~/.local/bin/butter"