#!/bin/bash
# این اسکریپت برای بروزرسانی یوزر و دیتابیس PostgreSQL
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
    CREATE DATABASE IF NOT EXISTS $POSTGRES_DB;
    CREATE USER IF NOT EXISTS $POSTGRES_USER WITH PASSWORD '$POSTGRES_PW';
    GRANT ALL PRIVILEGES ON DATABASE $POSTGRES_DB TO $POSTGRES_USER;
EOSQL
